version: 0.2

phases:
  install:  # Install dependencies
    runtime-versions:
      nodejs: 18
    commands:
      - npm install  # Install Node.js dependencies (if applicable)
      - pip install --upgrade aws-sam-cli  # Upgrade the AWS SAM CLI

  pre_build:
    commands:
      - sam validate --template-file template.yaml

  build:
    commands:
      #- cd frontend/mfe-contenedor && npm install && npm run build
      #- cd ../mfe-lista-usuarios && npm install && npm run build
      #- cd ../mfe-crear-usuario && npm install && npm run build
      #- cd ../mfe-sidebar && npm install && npm run build
      #- cd ../mfe-header && npm install && npm run build
      #- cd ../mfe-prueba && npm install && npm run build
      #- cd ../../

      - sam build --use-container

  post_build:
    commands:

      - sam package template.yaml --output-template-file packaged.yaml --s3-bucket s3-ipa-compilado
      - aws cloudformation deploy --template-file packaged.yaml --stack-name stack-prueba --capabilities CAPABILITY_NAMED_IAM --region us-east-1

      - aws s3 sync ./frontend/mfe-prueba/dist s3://s3-mf-prueba --delete
      - aws s3 sync ./frontend/mfe-registro-logueo-comprador/dist s3://s3-mf-registro-logueo-comprador --delete

artifacts:
  files:
    - packaged.yaml  # Include the packaged template file
