AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/createUser/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user
            Method: post

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/getUser/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: get

  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/getUsers/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/
            Method: get

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/updateUser/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        UpdateUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: put
            
  LambdaSubirArchivo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-subir-archivo/       
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaSubirArchivo:
          Type: Api
          Properties:
            Path: /user/SubirArchivo
            Method: post
            
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/deleteUser/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: delete

  LambdaListarClientes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-listar-clientes/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaListarClientes:
          Type: Api
          Properties:
            Path: /Usuarios/Compradores
            Method: get

  LambdaMostrarTendencias:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-mostrar-tendencias/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaMostrarTendencias:
          Type: Api
          Properties:
            Path: /Productos/Tendencias
            Method: get

  LambdaMostrarColeccionesNuevas:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-mostrar-colecciones-nuevas/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaMostrarColeccionesNuevas:
          Type: Api
          Properties:
            Path: /Productos/Colecciones/NuevasColecciones
            Method: get
           
  LambdaEliminarUsuario:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-eliminar-usuarios/       
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaEliminarUsuario:
          Type: Api
          Properties:
            Path: /Usuarios/EliminarUsuario
            Method: delete 

  LambdaObtenerTipoProductos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-obtener-tipo-productos/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaObtenerTipoProductos:
          Type: Api
          Properties:
            Path: /Productos/Tipos
            Method: get
           


lambdaobtenerproductoportexto:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-busqueda-producto-por-texto/       
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        lambdaobtenerproductoportexto:
          Type: Api
          Properties:
            Path: /lambdaobtenerproductoportexto
            Method: get

LambdaObtenerProductosporTipo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-busqueda-producto-por-tipo/       
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaObtenerProductosporTipo:
          Type: Api
          Properties:
            Path: /LambdaObtenerProductosporTipo
            Method: get

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
