AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
            
  LambdaSubirArchivo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-subir-archivo/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaSubirArchivo:
          Type: Api
          Properties:
            Path: /user/SubirArchivo
            Method: post
            
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/deleteUser/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: delete


  LambdaAdministradorCommunityManager:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-administrador-community-manager/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaAdministradorCommunityManager:
          Type: Api
          Properties:
            Path: /lambda-administrador-community-manager
            Method: get

  LambdaListarClientes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-listar-clientes/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaListarClientes:
          Type: Api
          Properties:
            Path: /Usuarios/Compradores
            Method: get

  LambdaMostrarTendencias:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-mostrar-tendencias/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaMostrarTendencias:
          Type: Api
          Properties:
            Path: /Productos/Tendencias
            Method: get

  LambdaMostrarColeccionesNuevas:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-mostrar-colecciones-nuevas/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaMostrarColeccionesNuevas:
          Type: Api
          Properties:
            Path: /Productos/Colecciones/NuevasColecciones
            Method: get
           
  LambdaObtenerTipoProductos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-obtener-tipo-producto/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaObtenerTipoProducto:
          Type: Api
          Properties:
            Path: /Productos/Tipos
            Method: get
           
  LambdaObtenerProductoPorTexto:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-busqueda-producto-por-texto/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaObtenerProductoPorTexto:
          Type: Api
          Properties:
            Path: /Productos/BuscarPorNombre
            Method: get

  LambdaEliminarUsuario:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-eliminar-usuarios/  
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaEliminarUsuario:
          Type: Api
          Properties:
            Path: /Usuarios/EliminarUsuario
            Method: delete 
  
  LambdaRegistrarComprador:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-registrar-comprador/  
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaRegistrarComprador:
          Type: Api
          Properties:
            Path: /Autenticacion/RegistroComprador
            Method: post  

  LambdaEditarUsuarios:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-editar-usuarios/       
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaEditarUsuarios:
          Type: Api
          Properties:
            Path: /Usuarios/EditarUsuarios
            Method: put 

  LambdaRegistrarContribuidor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-registrar-contribuidor/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaRegistrarContribuidor:
          Type: Api
          Properties:
            Path: /Autenticacion/RegisterContribuidor
            Method: post     

  LambdaLoginContribuidor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-login-contribuidor/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaLoginContribuidor:
          Type: Api
          Properties:
            Path: /Autenticacion/LoginContribuidor
            Method: post        

  LambdaLoginComprador:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/lambda-login-comprador/  
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaLoginComprador:
          Type: Api
          Properties:
            Path: /Autenticacion/LoginComprador
            Method: post 
Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
